# Generated by Django 5.1.2 on 2024-12-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('Customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=100)),
                ('Account_type', models.CharField(max_length=50)),
                ('Account_number', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Loan_type', models.CharField(max_length=30)),
                ('Loan_amount', models.IntegerField()),
            ],
        ),
    ]
